### ISSUE TITLE
Dúvida sobre a execução

### ISSUE THREAD

**Issue by rcarloslima** [advpl/advpl-unit-test#12]
Bom dia,

Primeiro parabéns pela iniciativa!!

Procedi da seguinte forma para tentar utilizar o plugin.

- Instalei o plugin
- Criei o teste herdando da classe FwDefaultTestCase.
- Cliquei no icone do plugin e não lista os testes.

Na documentação do vscode-dotnet-test-explorer fala que preciso criar o arquivo dotnet-test-explorer.testProjectPath , no advpl-unit-test também é necessário criar esse arquivo? qual seria o nome dele?

Obrigado,

Ruann Carlos

**Comment by killerall** [comment]
Bom dia,

Ainda não está disponivel o path com a base do test unit.

**Comment by rcarloslima** [comment]
ok, obrigado.
